### ekf config file ###
ekf_filter_node:
    ros__parameters:

        frequency: 30.0                   # 出力周期[30Hz]
        two_d_mode: false                 # 地面の変化を無視するか？
        publish_acceleration: true        # 加速度の値を出力するかどうか
        publish_tf: true                  # tf を出力するか

        # kf_filter_node が出力する topic 名を設定する
        map_frame: map                    # Defaults to "map" if unspecified
        odom_frame: odom                  # Defaults to "odom" if unspecified
        base_link_frame: base_footprint   # Defaults to "base_link" ifunspecified
        world_frame: odom                 # Defaults to the value of odom_frame if unspecified

        # odomトピックのどの値をフィルタで用いるのか？
        odom0: /odom
        odom0_config: [true, true, false,      # position of xyz
                       false, false, true,     # angle of rpy
                       true, true, false,      # velocity of xyz
                       false, false, true,     # angular velocity of rpy
                       true, true, false,]     # acceleraion of xyz

        # imuトピックのどの値をフィルタで用いるのか？
        imu0: /imu
        imu0_config: [true, true, false,       # position of xyz
                       false, false, true,     # angle of rpy
                       true, true, false,      # velocity of xyz
                       false, false, true,      # angular velocity of rpy
                       true, true, false]     # acceleraion of xyz